### ISSUE TITLE
batchDraw Exception

### ISSUE THREAD

**Issue by mrsions** [twicecircled/Android-Sprite-Batcher#2]
java.lang.IllegalArgumentException: capacity + offset > baseSize
　at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:37)
　at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:72)
　at com.twicecircled.spritebatcher.SpriteBatcher.batchDraw(SpriteBatcher.java:321)
　at com.twicecircled.spritebatcher.SpriteBatcher.onDrawFrame(SpriteBatcher.java:202)
　at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
　at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)

java.lang.IllegalArgumentException: capacity + offset > baseSize
　at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:37)
　at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:72)
　at com.twicecircled.spritebatcher.SpriteBatcher.batchDraw(SpriteBatcher.java:331)
　at com.twicecircled.spritebatcher.SpriteBatcher.onDrawFrame(SpriteBatcher.java:202)
　at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
　at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)

I do not know why this is happening

321: ByteBuffer ibb = ByteBuffer.allocateDirect(indices.length \* 2);
331: ByteBuffer vbb = ByteBuffer.allocateDirect(vertices.length \* 4);

Is this point

**Comment by twicecircled** [comment]
I'm really sorry but I'm very busy with other projects at the moment and
cannot look into this at this time. Perhaps someone else from the community
knows a fix and can make a pull request?

## 

Tim Wicksteed
Director
Twice Circled

www.twicecircled.com
tim@twicecircled.com Tim@twicecircled.com
Twitter http://www.twitter.com/twicecircled
